(define/contract (can-be-equal s1 s2)
  (-> string? string? boolean?)
  (define (swap02 s)
    (string (string-ref s 2)
            (string-ref s 1)
            (string-ref s 0)
            (string-ref s 3)))
  (define (swap13 s)
    (string (string-ref s 0)
            (string-ref s 3)
            (string-ref s 2)
            (string-ref s 1)))
  (or (string=? s1 s2)
      (string=? (swap02 s1) s2)
      (string=? (swap13 s1) s2)
      (string=? (swap13 (swap02 s1)) s2)))
